extraction:
  java:
    index:
      java_version: "16"
queries:
  - include: "*"
  - exclude: java/uncaught-number-format-exception
  - exclude: java/notify-instead-of-notify-all 
  - exclude: java/duplicate-method
  - exclude: java/local-temp-file-or-directory-information-disclosure
