extraction:
  java:
    index:
      java_version: "9"
      build_command:
        ./gradlew -x test build --no-daemon --info
queries:
  - include: "*"
  - exclude: java/uncaught-number-format-exception
  - exclude: java/notify-instead-of-notify-all 
