language: java
os:
  - linux
services:
  - docker
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
install:
  - ./gradlew assemble --stacktrace --info
script:
  - ./gradlew check --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
