language: java
os:
  - linux
services:
  - docker
jdk:
  - oraclejdk9
  - openjdk10
  - openjdk11
install:
  - travis_retry ./gradlew --info dependencies --refresh-dependencies
script:
  - ./gradlew build --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
